=== PASTAplus/PASTA/DataPackageManager/WebRoot/xml/qualityReportSchema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
  xmlns="eml://ecoinformatics.org/qualityReport"
  targetNamespace="eml://ecoinformatics.org/qualityReport"
  elementFormDefault="unqualified" attributeFormDefault="unqualified">
  
  <xs:annotation>
    <xs:documentation>This XML Schema is used to validate XML Quality Report
      documents generated by the quality reporting facilities of the Data Manager 
      Library code. A quality report contains zero or one datasetReport elements,
      followed by zero or more entityReport elements. Both datasetReport and
      entityReport elements contain zero or more qualityCheck elements. Each
      qualityCheck element captures the information from a single quality metric
      performed on EML metadata, on data, or on the congruency of the metadata 
      to the data.
    </xs:documentation>
  </xs:annotation>

  <!-- qualityReport document element -->
  <xs:element name="qualityReport">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="creationDate"  minOccurs="0" maxOccurs="1" />
        <xs:element ref="packageId"     minOccurs="0" maxOccurs="1" />
        <xs:element ref="includeSystem" minOccurs="0" maxOccurs="unbounded" />
        <xs:element ref="datasetReport" minOccurs="0" />
        <xs:element ref="entityReport"  minOccurs="0" maxOccurs="unbounded" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <!-- end of qualityReport document element -->
  
  <!-- datasetReport element -->
  <xs:element name="datasetReport">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="qualityCheck" minOccurs="0" maxOccurs="unbounded" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  
  <!-- entityReport element -->
  <xs:element name="entityReport">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="entityName" />
        <xs:element ref="entityId"     minOccurs="0" />
        <xs:element ref="qualityCheck" minOccurs="0" maxOccurs="unbounded" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <!-- qualityCheck information -->
  <xs:element name="qualityCheck">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="identifier" />
        <xs:element ref="name" />
        <xs:element ref="description"  minOccurs="0" />
        <xs:element ref="emlPath"      minOccurs="0" />
        <xs:element ref="expected"     minOccurs="0" />
        <xs:element ref="found"        minOccurs="0" />
        <xs:element ref="status"       minOccurs="0" maxOccurs="1" />
        <xs:element ref="explanation"  minOccurs="0" />
        <xs:element ref="suggestion"   minOccurs="0" />
        <xs:element ref="reference"    minOccurs="0" />
      </xs:sequence>
      <xs:attribute name="qualityType" use="optional" default="congruency">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="congruency"/>
            <xs:enumeration value="data"/>
            <xs:enumeration value="metadata"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute>
      <xs:attribute name="statusType" use="required">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="info"/>
            <xs:enumeration value="warn"/>
            <xs:enumeration value="error"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute>
      <xs:attribute name="system" type="xs:string" use="required"/>
    </xs:complexType>
  </xs:element>
  
  <!-- Enumerated type: status -->
  <xs:element name="status">
    <xs:simpleType>
      <xs:restriction base="xs:string">
        <xs:enumeration value="notChecked" />
        <xs:enumeration value="valid" />
        <xs:enumeration value="info" />
        <xs:enumeration value="warn" />
        <xs:enumeration value="error" />
      </xs:restriction>
    </xs:simpleType>
  </xs:element>

  <xs:element name="creationDate" type="xs:dateTime" />
  <xs:element name="description"  type="xs:string" />
  <xs:element name="emlPath"      type="xs:string" />
  <xs:element name="entityId"     type="xs:string" />
  <xs:element name="entityName"   type="xs:string" />
  <xs:element name="expected"     type="xs:string" />
  <xs:element name="explanation"  type="xs:string" />
  <xs:element name="found"        type="xs:string" />
  <xs:element name="identifier"   type="xs:string" />
  <xs:element name="name"         type="xs:string" />
  <xs:element name="packageId"    type="xs:string" />
  <xs:element name="reference"    type="xs:string" />
  <xs:element name="includeSystem" type="xs:string" />
  <xs:element name="suggestion"   type="xs:string" />

</xs:schema>

=== PASTAplus/PASTA/DataPackageManager/test/data/qualityReportWithoutError.xml
<?xml version="1.0" encoding="UTF-8"?>
<qr:qualityReport
  xmlns="eml://ecoinformatics.org/qualityReport"
  xmlns:qr="eml://ecoinformatics.org/qualityReport"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="eml://ecoinformatics.org/qualityReport http://svn.lternet.edu/svn/NIS/documents/schemas/quality/qualityReportSchema.xsd"
  >
  <creationDate>2012-01-19T11:48:42</creationDate>
  <packageId>knb-lter-lno.1957.1</packageId>
  <includeSystem>knb</includeSystem>
  <includeSystem>lter</includeSystem>
  <datasetReport>
  </datasetReport>
  <entityReport>
    <entityName>1_NoneSuchBugCount</entityName>
    <entityId>xyz</entityId>
    <qualityCheck qualityType="congruency" system="knb" statusType="error" >
      <identifier>onlineURLs</identifier>
      <name>Online URLs are live</name>
      <description>Check that online URLs return something</description>
      <expected>true</expected>
      <found>true</found>
      <status>valid</status>
      <explanation>Succeeded in accessing URL: <![CDATA[http://trachyte.lternet.edu:8080/test/NoneSuchBugCount.txt]]></explanation>
      <suggestion></suggestion>
      <reference></reference>
    </qualityCheck>
    <qualityCheck qualityType="metadata" system="knb" statusType="error" >
      <identifier>databaseTableCreated</identifier>
      <name>Create database table</name>
      <description>Status of creating a database table</description>
      <expected>A database table is expected to be generated from the EML attributes.</expected>
      <found>A database table was generated from the attributes description</found>
      <status>valid</status>
      <explanation>CREATE TABLE _1_NoneSuchBugCount(fld TEXT,year TIMESTAMP,sppm2 FLOAT);</explanation>
      <suggestion></suggestion>
      <reference></reference>
    </qualityCheck>
    <qualityCheck qualityType="data" system="knb" statusType="info" >
      <identifier>displayDownloadData</identifier>
      <name>Display some data</name>
      <description>Display the first row of data</description>
      <expected>One row of data should be displayed</expected>
      <found><![CDATA[Blue Field, 1998, 4.5]]></found>
      <status>info</status>
      <explanation></explanation>
      <suggestion></suggestion>
      <reference></reference>
    </qualityCheck>
    <qualityCheck qualityType="congruency" system="knb" statusType="error" >
      <identifier>dataLoadStatus</identifier>
      <name>Data load status</name>
      <description>Status of loading the data table into a database</description>
      <expected>No errors expected during data loading or data loading was not attempted for this data entity</expected>
      <found>The data table loaded successfully into a database</found>
      <status>valid</status>
      <explanation></explanation>
      <suggestion></suggestion>
      <reference></reference>
    </qualityCheck>
    <qualityCheck qualityType="congruency" system="knb" statusType="error" >
      <identifier>numberOfRecords</identifier>
      <name>Number of records check</name>
      <description>Compare number of records specified in metadata to number of records found in data</description>
      <expected>42</expected>
      <found>42</found>
      <status>valid</status>
      <explanation>The expected number of records (42) was found in the data table.</explanation>
      <suggestion></suggestion>
      <reference></reference>
    </qualityCheck>
  </entityReport>
</qr:qualityReport>

=== PASTAplus/PASTA/DataPackageManager/test/data/qualityReportWithError.xml
<?xml version="1.0" encoding="UTF-8"?>
<qr:qualityReport
  xmlns="eml://ecoinformatics.org/qualityReport"
  xmlns:qr="eml://ecoinformatics.org/qualityReport"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="eml://ecoinformatics.org/qualityReport http://svn.lternet.edu/svn/NIS/documents/schemas/quality/qualityReportSchema.xsd"
  >
  <creationDate>2012-01-24T11:12:36</creationDate>
  <packageId>knb-lter-lno.2002005.6</packageId>
  <includeSystem>knb</includeSystem>
  <includeSystem>lter</includeSystem>
  <datasetReport>
  </datasetReport>
  <entityReport>
    <entityName>npp_grg.dat</entityName>
    <qualityCheck qualityType="congruency" system="knb" statusType="error" >
      <identifier>onlineURLs</identifier>
      <name>Online URLs are live</name>
      <description>Check that online URLs return something</description>
      <expected>true</expected>
      <found>true</found>
      <status>valid</status>
      <explanation>Succeeded in accessing URL: <![CDATA[http://jornada-www.nmsu.edu/studies/lter/datasets/climate/npp_grg/npp_grg.dat]]></explanation>
      <suggestion></suggestion>
      <reference></reference>
    </qualityCheck>
    <qualityCheck qualityType="metadata" system="knb" statusType="error" >
      <identifier>databaseTableCreated</identifier>
      <name>Create database table</name>
      <description>Status of creating a database table</description>
      <expected>A database table is expected to be generated from the EML attributes.</expected>
      <found>A database table was generated from the attributes description</found>
      <status>valid</status>
      <explanation>CREATE TABLE npp_grg_dat("date" TIMESTAMP,"z" TEXT,"site" TEXT,"pp_mm" FLOAT,"p" TEXT,"p_in" FLOAT,"loc_gage" TEXT,"id_gage" TEXT,"type" TEXT,"ownr" TEXT);</explanation>
      <suggestion></suggestion>
      <reference></reference>
    </qualityCheck>
    <qualityCheck qualityType="data" system="knb" statusType="info" >
      <identifier>displayDownloadData</identifier>
      <name>Display some data</name>
      <description>Display the first row of data</description>
      <expected>One row of data should be displayed</expected>
      <found><![CDATA[07/25/1989, M, NORT, 28.4, 8, 1.12, E   jer,past4A, rabbit-dsrg, dsrg, in us]]></found>
      <status>info</status>
      <explanation></explanation>
      <suggestion></suggestion>
      <reference></reference>
    </qualityCheck>
    <qualityCheck qualityType="congruency" system="knb" statusType="error" >
      <identifier>dataLoadStatus</identifier>
      <name>Data load status</name>
      <description>Status of loading the data table into a database</description>
      <expected>No errors expected during data loading or data loading was not attempted for this data entity</expected>
      <found>One or more errors occurred during data loading</found>
      <status>error</status>
      <explanation>Data WELL is NOT a FLOAT : For input string: "WELL"
SQL insert string:
INSERT INTO npp_grg_dat("date","z","site","pp_mm","p","p_in","loc_gage","id_gage","type","ownr") VALUES (to_timestamp('07/25/','mm/dd/yyyy'),'P','SMAL',10.1,'0',0.4,'.   cdrrc,past2','vine mesq playa-dsr','dsrg','in cd');</explanation>
      <suggestion></suggestion>
      <reference></reference>
    </qualityCheck>
  </entityReport>
</qr:qualityReport>
